GET http://localhost:5171/games

###

GET http://localhost:5171/games/4

###

POST http://localhost:5171/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genre": "Kids and Family",
    "price": 19.99,
    "releaseDate": "2011-11-18"
}

###

PUT http://localhost:5171/games/2
Content-Type: application/json

  {
    "name": "Cyberpunk 2088",
    "genre": "Fighting",
    "price": 9.99,
    "releaseDate": "2019-07-15"
  }

###

DELETE http://localhost:5171/games/2
